@ECHO OFF
@ECHO.

::1
C:\TABLETY\ADB\adb shell input tap 650 320
::4
C:\TABLETY\ADB\adb shell input tap 650 400
::2
C:\TABLETY\ADB\adb shell input tap 735 320
::5
C:\TABLETY\ADB\adb shell input tap 735 400
::3
C:\TABLETY\ADB\adb shell input tap 820 320

ping 1.1.1.1 -n 1 -w 1000

::1
C:\TABLETY\ADB\adb shell input tap 650 320
::4
C:\TABLETY\ADB\adb shell input tap 650 400
::2
C:\TABLETY\ADB\adb shell input tap 735 320
::5
C:\TABLETY\ADB\adb shell input tap 735 400
::3
C:\TABLETY\ADB\adb shell input tap 820 320


PING 1.1.1.1 -n 1 -w 1000


::1
C:\TABLETY\ADB\adb shell input tap 650 320
::4
C:\TABLETY\ADB\adb shell input tap 650 400
::2
C:\TABLETY\ADB\adb shell input tap 735 320
::5
C:\TABLETY\ADB\adb shell input tap 735 400
::3
C:\TABLETY\ADB\adb shell input tap 820 320
@ECHO OFF
PING 1.1.1.1 -n 1 -w 3000


::K
C:\TABLETY\ADB\adb shell input tap 735 520
::A
C:\TABLETY\ADB\adb shell input tap 155 520
::T
C:\TABLETY\ADB\adb shell input tap 460 420
::A
C:\TABLETY\ADB\adb shell input tap 155 520
::R
C:\TABLETY\ADB\adb shell input tap 375 420
::Z
C:\TABLETY\ADB\adb shell input tap 170 595
::Y
C:\TABLETY\ADB\adb shell input tap 550 420
::N
C:\TABLETY\ADB\adb shell input tap 595 595
::A
C:\TABLETY\ADB\adb shell input tap 155 520
::.
C:\TABLETY\ADB\adb shell input tap 830 595


::G
C:\TABLETY\ADB\adb shell input tap 480 520
::O
C:\TABLETY\ADB\adb shell input tap 800 420
::G
C:\TABLETY\ADB\adb shell input tap 480 520
::L
C:\TABLETY\ADB\adb shell input tap 815 520
::O
C:\TABLETY\ADB\adb shell input tap 800 420
::Z
C:\TABLETY\ADB\adb shell input tap 170 595
::A
C:\TABLETY\ADB\adb shell input tap 155 520

::HAS£O
ping 1.1.1.1 -n 1 -w 200
C:\TABLETY\ADB\adb shell input tap 620 130
::J
C:\TABLETY\ADB\adb shell input tap 656 520
::V
C:\TABLETY\ADB\adb shell input tap 430 595
::M
C:\TABLETY\ADB\adb shell input tap 675 595
::X
C:\TABLETY\ADB\adb shell input tap 260 595
::U
C:\TABLETY\ADB\adb shell input tap 640 420
::Y
C:\TABLETY\ADB\adb shell input tap 550 420
::G
C:\TABLETY\ADB\adb shell input tap 480 520
::P
C:\TABLETY\ADB\adb shell input tap 870 420
::Shift
C:\TABLETY\ADB\adb shell input tap 50 511
::6
@ECHO OFF
ping 1.1.1.1 -n 1 -w 400 >nul
C:\TABLETY\ADB\adb shell input tap 520 420
@ECHO OFF
ping 1.1.1.1 -n 1 -w 200 >nul
C:\TABLETY\ADB\adb shell input tap 506 187

CALL C:\TABLETY\ARIES785\ARIES785_KD-DOR.BAT

