@ECHO OFF
@ECHO.

::1
C:\TABLETY\ADB\adb shell input tap 792 320
::4
C:\TABLETY\ADB\adb shell input tap 792 410
::2
C:\TABLETY\ADB\adb shell input tap 870 320
::5
C:\TABLETY\ADB\adb shell input tap 870 410
::3
C:\TABLETY\ADB\adb shell input tap 976 320

ping 1.1.1.1 -n 1 -w 1000

::1
C:\TABLETY\ADB\adb shell input tap 792 320
::4
C:\TABLETY\ADB\adb shell input tap 792 410
::2
C:\TABLETY\ADB\adb shell input tap 870 320
::5
C:\TABLETY\ADB\adb shell input tap 870 410
::3
C:\TABLETY\ADB\adb shell input tap 976 320

ping 1.1.1.1 -n 1 -w 1000


::1
C:\TABLETY\ADB\adb shell input tap 792 320
::4
C:\TABLETY\ADB\adb shell input tap 792 410
::2
C:\TABLETY\ADB\adb shell input tap 870 320
::5
C:\TABLETY\ADB\adb shell input tap 870 410
::3
C:\TABLETY\ADB\adb shell input tap 976 320

ping 1.1.1.1 -n 1 -w 3000


::K
C:\TABLETY\ADB\adb shell input tap 925 534
::A
C:\TABLETY\ADB\adb shell input tap 195 534
::T
C:\TABLETY\ADB\adb shell input tap 584 451
::A
C:\TABLETY\ADB\adb shell input tap 195 534
::R
C:\TABLETY\ADB\adb shell input tap 474 451
::Z
C:\TABLETY\ADB\adb shell input tap 222 634
::Y
C:\TABLETY\ADB\adb shell input tap 684 458
::N
C:\TABLETY\ADB\adb shell input tap 751 610
::A
C:\TABLETY\ADB\adb shell input tap 195 534
::.
C:\TABLETY\ADB\adb shell input tap 1060 624


::G
C:\TABLETY\ADB\adb shell input tap 626 534
::O
C:\TABLETY\ADB\adb shell input tap 989 458
::G
C:\TABLETY\ADB\adb shell input tap 626 534
::L
C:\TABLETY\ADB\adb shell input tap 1020 537
::O
C:\TABLETY\ADB\adb shell input tap 989 458
::Z
C:\TABLETY\ADB\adb shell input tap 222 634
::A
C:\TABLETY\ADB\adb shell input tap 195 534

::HAS£O
ping 1.1.1.1 -n 1 -w 200
C:\TABLETY\ADB\adb shell input tap 737 132
::J
C:\TABLETY\ADB\adb shell input tap 823 547
::V
C:\TABLETY\ADB\adb shell input tap 528 625
::M
C:\TABLETY\ADB\adb shell input tap 849 614
::X
C:\TABLETY\ADB\adb shell input tap 324 610
::U
C:\TABLETY\ADB\adb shell input tap 791 460
::Y
C:\TABLETY\ADB\adb shell input tap 686 445
::G
C:\TABLETY\ADB\adb shell input tap 626 534
::P
C:\TABLETY\ADB\adb shell input tap 1111 452
::Shift
C:\TABLETY\ADB\adb shell input tap 66 531
::6
@ECHO OFF
ping 1.1.1.1 -n 1 -w 400 >nul
C:\TABLETY\ADB\adb shell input tap 686 441
@ECHO OFF
ping 1.1.1.1 -n 1 -w 200 >nul
::zaloguj
C:\TABLETY\ADB\adb shell input tap 644 183

CALL C:\TABLETY\ARIES70\ARIES70_DOR.BAT

