@ECHO OFF
@ECHO.

::1
C:\TABLETY\ADB\adb shell input tap 660 240
::4
C:\TABLETY\ADB\adb shell input tap 660 320
::2
C:\TABLETY\ADB\adb shell input tap 736 240
::5
C:\TABLETY\ADB\adb shell input tap 736 320
::3
C:\TABLETY\ADB\adb shell input tap 830 240

ping 1.1.1.1 -n 1 -w 1000

::1
C:\TABLETY\ADB\adb shell input tap 660 240
::4
C:\TABLETY\ADB\adb shell input tap 660 320
::2
C:\TABLETY\ADB\adb shell input tap 736 240
::5
C:\TABLETY\ADB\adb shell input tap 736 320
::3
C:\TABLETY\ADB\adb shell input tap 830 240

ping 1.1.1.1 -n 1 -w 1000


::1
C:\TABLETY\ADB\adb shell input tap 660 240
::4
C:\TABLETY\ADB\adb shell input tap 660 320
::2
C:\TABLETY\ADB\adb shell input tap 736 240
::5
C:\TABLETY\ADB\adb shell input tap 736 320
::3
C:\TABLETY\ADB\adb shell input tap 830 240

ping 1.1.1.1 -n 1 -w 3000


::K
C:\TABLETY\ADB\adb shell input tap 740 410
::A
C:\TABLETY\ADB\adb shell input tap 90 410
::T
C:\TABLETY\ADB\adb shell input tap 410 334
::A
C:\TABLETY\ADB\adb shell input tap 90 410
::R
C:\TABLETY\ADB\adb shell input tap 330 344
::Z
C:\TABLETY\ADB\adb shell input tap 140 475
::Y
C:\TABLETY\ADB\adb shell input tap 510 340
::N
C:\TABLETY\ADB\adb shell input tap 620 470
::A
C:\TABLETY\ADB\adb shell input tap 90 410
::.
C:\TABLETY\ADB\adb shell input tap 880 460


::G
C:\TABLETY\ADB\adb shell input tap 460 390
::O
C:\TABLETY\ADB\adb shell input tap 780 333
::G
C:\TABLETY\ADB\adb shell input tap 460 390
::L
C:\TABLETY\ADB\adb shell input tap 830 400
::O
C:\TABLETY\ADB\adb shell input tap 780 333
::Z
C:\TABLETY\ADB\adb shell input tap 140 475
::A
C:\TABLETY\ADB\adb shell input tap 90 410

::HAS£O
ping 1.1.1.1 -n 1 -w 200
C:\TABLETY\ADB\adb shell input tap 600 143
::J
C:\TABLETY\ADB\adb shell input tap 644 400
::V
C:\TABLETY\ADB\adb shell input tap 410 460
::M
C:\TABLETY\ADB\adb shell input tap 710 460
::X
C:\TABLETY\ADB\adb shell input tap 240 465
::U
C:\TABLETY\ADB\adb shell input tap 600 330
::Y
C:\TABLETY\ADB\adb shell input tap 500 330
::G
C:\TABLETY\ADB\adb shell input tap 460 390
::P
C:\TABLETY\ADB\adb shell input tap 870 330
::Shift
C:\TABLETY\ADB\adb shell input tap 50 530
::6
@ECHO OFF
ping 1.1.1.1 -n 1 -w 400 >nul
C:\TABLETY\ADB\adb shell input tap 500 330
@ECHO OFF
ping 1.1.1.1 -n 1 -w 200 >nul
::zaloguj
C:\TABLETY\ADB\adb shell input tap 510 180

CALL C:\TABLETY\IMPERIUS\IMPERIUS_DOR.BAT

